version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo-data:
